import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="/favicon.png"
        type="image/<generated>"
        sizes="<generated>"
      />
      <title>UPBuen Viaje</title>
      <body>{children}</body>
    </html>
  );
}
