import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import { Footer, NavBar } from "@/components";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="/favicon.png"
        type="image/<generated>"
        sizes="<generated>"
      />
      <title>UPBuen Viaje</title>
      <body className="min-h-full bg-white">
        <Providers>
          <NavBar></NavBar>
          {children}
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
}
